mongodb:
  primary:
    host: localhost
    port: 27017
    database: first
    username: apifirst
    password: pa55w0rd
  secondary:
    host: localhost
    port: 27017
    database: second
    username: apisecond
    password: pa55w0rd

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  application:
    name: spring-boot-multi-mongo

server:
  port: 2135

logging:
  level:
    root: DEBUG
